### ISSUE TITLE
Work with httptest package

### ISSUE THREAD

**Issue by yookoala** [yookoala/restit#1]
RESTit is based on [napping](http://github.com/jmcvetta/napping), which generates real http requests. It aims to be a real REST client, so that isn't its problem. But RESTit aims to be a  testing library, it would be nice if it can work with fake server created by core [httptest](http://golang.org/pkg/net/http/httptest/) package.

To do so, I can think of 2 possible options:

  1. Rewrite the connection layer without napping.
  2. Find a way to get napping's resulting http request (of the http package) so it could be send to test server.

**Comment by omeid** [comment]
Seems like you haven't work on this project for a long time, but if you still want an http testing framework that is richer than the net/http/httptest, I just started working on an [extension of /net/http/httptest](https://github.com/omeid/httptest)` which is inspired by frisbyjs. :)

**Comment by yookoala** [comment]
Thanks. It took me sometimes to actually know how to work with `httptest`. Will give this library an update soon.

I'll take a look at the extension also. Thanks for letting me know :-)

**Comment by yookoala** [comment]
Demonstrated full use of `httptest` in the new example. Feature fulfilled.
